//> using scala 3.3.3
//> using plugin org.scalus:scalus-plugin_3:0.6.2-SNAPSHOT
//> using dep org.scalus:scalus_3:0.6.1+45-0afdd1cc+20240525-1903-SNAPSHOT
//> using dep org.scalus:scalus-bloxbean-cardano-client-lib_3:0.6.1+45-0afdd1cc+20240525-1903-SNAPSHOT
//> using dep org.slf4j:slf4j-simple:2.0.13
//> using dep org.bouncycastle:bcprov-jdk18on:1.78.1
//> using dep net.i2p.crypto:eddsa:0.3.0
//> using dep com.bloxbean.cardano:cardano-client-lib:0.5.1
//> using dep com.bloxbean.cardano:cardano-client-backend-blockfrost:0.5.1
//> using dep com.softwaremill.sttp.tapir::tapir-core:1.10.7
//> using dep com.softwaremill.sttp.tapir::tapir-files:1.10.7
//> using dep com.softwaremill.sttp.tapir::tapir-netty-server-sync:1.10.7
//> using dep com.softwaremill.sttp.tapir::tapir-swagger-ui-bundle:1.10.7
//> using test.dep org.scalameta::munit::1.0.0
//> using test.dep org.scalameta::munit-scalacheck::1.0.0
//> using test.dep org.scalacheck::scalacheck::1.18.0
